### ISSUE TITLE
needs urgent fix

### ISSUE THREAD

**Issue by CDitzel** [Jafar874/ASIC-Profitability-and-Bitcoin-Price#1]
https://github.com/Jafar874/ASIC-Profitability-and-Bitcoin-Price/blob/356b68d09afe462847c8dfb0ddd3dce261dd94a3/ASIC_profitability.py#L43

this overflows for multiple combinations of input

**Comment by Jafar874** [comment]
Workaround implemented.
Real fix still outstanding.
